---
- name: install extensions
  become: yes
  become_user: '{{ item.0.username }}'
  visual_studio_code_install_extension:
    executable: '{{ visual_studio_code_exe }}'
    userdatadir: '{{ item.0.visual_studio_code_userdata_dir | default("") }}'
    name: '{{ item.1 }}'
  with_subelements:
    - '{{ users }}'
    - visual_studio_code_extensions
    - skip_missing: yes
  loop_control:
    label: '{{ item.0.username }}: {{ item.1 }}'
