---
- name: install dependencies (dnf)
  become: yes
  dnf:
    name:
      - libX11-xcb
      - which
    state: present

- name: install VS Code repo (dnf)
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: "{{ packages_microsoft_com }}/yumrepos/vscode"
    gpgkey: "{{ packages_microsoft_com }}/keys/microsoft.asc"
    gpgcheck: yes

- name: install VS Code (dnf)
  become: yes
  dnf:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('-' + visual_studio_code_version, '') }}"
    state: present
